name: Workflow [OUS]

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: build output destination
        options:
        - artifact_dev
        - artifact_prod_vnv
        - e_store_enterprise
        - e_store_prod_vnv
        - app_store        
      version:
        description: 'App version'
        required: true
        default: '0.0.0'
      deploy:
        description: 'deply for artifactory or e-store'
        required: true
        default: '0.0.0'
      issue_key:
        description: 'task/bug number'
        required: true
        default: 'G6X-'
      region: 
        type: choice
        description: OUS Region
        options:
        - r01
        - r02
        - r03
        - r06
        - r07
        - r08
        - r09
        - r10
        - r11
      unit: 
        type: choice
        description: CGM Unit
        options:
        - mgdl
        - mmol     
jobs:

  permission:
    uses: pancho-romero-dexcom/ios_cgm_workflow_poc/.github/workflows/reusable_permission.yml@main
    with:
      destination: ${{ github.event.inputs.destination }}
    secrets:
      who_we_trust: ${{ secrets.OUS_APP_STORE_OWNER }}
      
  input_validation:
    needs: permission
    uses: pancho-romero-dexcom/ios_cgm_workflow_poc/.github/workflows/reusable_input_validation.yml@main
    with:
      destination: ${{ github.event.inputs.destination }}
      version: ${{ github.event.inputs.version }}
      deploy: ${{ github.event.inputs.deploy }}
      issue_key: ${{ github.event.inputs.issue_key }}
    
      