name  : ♻️-Permission [US & OUS]

on:
  workflow_call:
    inputs:
      destination:
        description: build output destination
        type: string
    secrets:
      who_we_trust:
        required: true

jobs:    

  run_workflow: 
    runs-on: self-hosted
    steps:

    - name: validate permision for artifact
      if: ${{ github.event.inputs.destination == 'artifact_dev' || github.event.inputs.version == 'artifact_prod_vnv' }}
      run: | 
        echo "✅ Everybody can run for artifacts "
        exit 0
    
    - name: validate permision for e-store 
      if: ${{ github.event.inputs.destination == 'e_store_enterprise' || github.event.inputs.destination == 'e_store_prod_vnv' }}
      run: | 
        echo "✅ Everybody can run for e-store"
        exit 0    
    
    - name: validate for app-store
      if: ${{ github.event.inputs.destination == 'app_store' }}
      run: | 
        if ${{ github.actor != secrets.who_we_trust }} 
        then 
          echo "🚫 You are not US_APP_STORE_OWNER, you can not trigger this workflow for app store, verify the secrets setup"
          
          exit 1
        fi        
        exit 0