name  : ♻️  (US) Build

on:
  workflow_call:
    inputs:
      destination:
        description: build output destination
        type: string
      version:
        description: 'App version'
        type: string
      deploy:
        description: 'App version structure on artifactory or e-store'
        type: string
      issue_key:
        description: 'task/bug number'
        type: string
jobs:     

  checkout:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.destination == 'artifact_dev' || github.event.inputs.version == 'artifact_prod_vnv'}}
    
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.destination == 'e_store_enterprise' || github.event.inputs.version == 'e_store_enterprise'}}
    
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.destination == 'app_store'}}
      
      - name: checkout ready
        run: echo "✅ branch is ready to build"

  fastlane:
    needs: checkout 
    runs-on: self-hosted    
    steps:

    - name: build for artifact dev
      if: ${{ github.event.inputs.destination == 'artifact_dev' }}
      run: | 
        echo "bundle exec fastlane g6_enterprise version:${{ github.event.inputs.version }} deploy_artifactory:${{ github.event.inputs.deploy }} issue:${{ github.event.inputs.issue }}"
        exit 0

    - name: build for artifact prod_vnv
      if: ${{ github.event.inputs.version == 'artifact_prod_vnv' }}
      run: | 
        echo "bundle exec fastlane g6_enterprise_stableintegration version:${{ github.event.inputs.version }} deploy_artifactory:\"${{ github.event.inputs.deploy }}\" issue:${{ github.event.inputs.issue }}"
        exit 0

    - name: build for e-store enterprice
      if: ${{ github.event.inputs.destination == 'e_store_enterprise' }}
      run: | 
        echo "bundle exec fastlane g6_enterprise version:${{ github.event.inputs.version }} obfuscate:false test:true leave_artifacts:true deploy_estore:${{ github.event.inputs.deploy }}" 
        exit 0
    
    - name: build for e-store prod-vnv
      if: ${{ github.event.inputs.destination == 'e_store_prod_vnv' }}
      run: | 
        echo "bundle exec fastlane g6_enterprise_stableintegration version:${{ github.event.inputs.version }} obfuscate:false test:true leave_artifacts:true deploy_estore:${{ github.event.inputs.deploy }}"
        exit 0

    - name: build for app-store
      if: ${{ github.event.inputs.destination == 'app_store' }}
      run: | 
        echo "bundle exec fastlane g6_store version:${{ github.event.inputs.version }} leave_artifacts:true deploy_itunes:true"  
        exit 0

  log:
    needs: fastlane 
    runs-on: self-hosted    
    steps:
    - name: actions/upload-artifact@v2
      run: |
        echo "uploading artifact"