name: (US) Build



on:
  workflow_call:
    inputs:
      destination:
        description: build output destination
        type: string
      version:
        description: 'App version'
        type: string
      deploy:
        description: 'App version structure on artifactory or e-store'
        type: string
      issue:
        description: 'task/bug number'
        type: string
jobs:     

  checkout:
    runs-on: self-hosted    
    steps:
    - uses: actions/checkout@v2

  fastlane_build:
    needs: checkout
    runs-on: self-hosted    
    steps:

    - name: build for artifact dev
      if: ${{ github.event.inputs.destination == 'artifact_dev' }}
      run: | 
        echo "building for development"
        exit 0

    - name: build for artifact prod_vnv
      if: ${{ github.event.inputs.version == 'artifact_prod_vnv' }}
      run: | 
        echo "building for development"
        exit 0

    - name: build for e-store enterprice
      if: ${{ github.event.inputs.destination == 'e_store_enterprise' }}
      run: | 
        echo "building for e-store" 
        exit 0
    
    - name: build for e-store prod-vnv
      if: ${{ github.event.inputs.destination == 'e_store_prod_vnv' }}
      run: | 
        echo "building for e-store"
        exit 0

    - name: build for app-store
      if: ${{ github.event.inputs.destination == 'app_store' }}
      run: | 
        echo "building for app-store"  
        exit 0

  fastlane_log:
    runs-on: self-hosted    
    steps:
    - name: actions/upload-artifact@v2