name  : ♻️  (US) Permission

on:
  workflow_call:
    inputs:
      destination:
        description: build output destination
        type: string
    secrets:
      owner:
        required: true
env: 
  WHO_TO_TRUST: ${{secrets.owner}}

jobs:     

  run_workflow: 
    runs-on: self-hosted
    steps:

    - name: validate permision for artifact
      if: ${{ github.event.inputs.destination == 'artifact_dev' || github.event.inputs.version == 'artifact_prod_vnv' }}
      run: | 
        echo "✅ Everybody can run for artifacts"
        exit 0
    
    - name: validate permision for e-store 
      if: ${{ github.event.inputs.destination == 'e_store_enterprise' || github.event.inputs.destination == 'e_store_prod_vnv' }}
      run: | 
        echo "✅ Everybody can run for artifacts"
        exit 0    
    
    - name: validate for app-store
      if: ${{ github.event.inputs.destination == 'app_store' }}
      run: | 
        if ${{ github.actor != env.WHO_TO_TRUST }} 
        then 
          echo "🚫 You are not ${{ env.WHO_TO_TRUST }}, you can not trigger this workflow for app store"
          
          exit 1
        fi        
        exit 0