name: (US) Workflow

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: build output destination
        options:
        - artifact_dev
        - artifact_prod_vnv
        - e_store_enterprise
        - e_store_prod_vnv
        - app_store
      version:
        description: 'App version'
        required: true
        default: '0.0.0'
      deploy:
        description: 'App version structure on artifactory or e-store'
        required: true
        default: '0.0.0'
      issue:
        description: 'task/bug number'
        required: true
        default: 'G6X-'
jobs:

  input_validation:
    uses: pancho-romero-dexcom/ios_cgm_workflow_poc/.github/workflows/us_input_validation.yml@main
    with:
      destination: ${{ github.event.inputs.destination }}
      version: ${{ github.event.inputs.version }}
      deploy: ${{ github.event.inputs.deploy }}
      issue: ${{ github.event.inputs.issue }}
    
  build:
    needs: input_validation
    uses: pancho-romero-dexcom/ios_cgm_workflow_poc/.github/workflows/us_build.yml@main
    with:
      destination: ${{ github.event.inputs.destination }}
      version: ${{ github.event.inputs.version }}
      deploy: ${{ github.event.inputs.deploy }}
      issue: ${{ github.event.inputs.issue }}
