name: US Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: destination
        options:
        - artifact_dev
        - artifact_prod_vnv
        - e_store
        - app_store
      version:
        description: 'App version'
        required: true
        default: '0.0.0'
      deploy_artifactory:
        description: 'App version structure on artifactory'
        required: true
        default: '0.0.0'
jobs:

  validate_inputs:
    runs-on: self-hosted
    steps:
    
    # Validate inputs
    - name: validate inputs
      run: |
        exit 1



  build_app:
    runs-on: self-hosted
    needs: validate_inputs
    steps:
    
    # Validate inputs
    - name: validate inputs
      run: |
        exit 1



    - name: bundle install
      run: echo "installing bundle"

  fastlane:
    uses: pancho-romero-dexcom/ios_cgm_workflow_poc/.github/workflows/fastlane_log.yml@main
    needs: build_app
    with:
      name: pancho
      path: ./
      
      
    
      
  
